src/main/java/org/bitbucket/dms/model/AttrListValue.java
package org.bitbucket.dms.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

@Entity
@NamedQuery(name = "AttrListValue.getAll", query = "SELECT a FROM AttrListValue a")
@Table(name = "attr_list_value")
public class AttrListValue {

    @Id
    @Column(name = "attribute_id")
    private Long attributeId;
    @Column(name = "list_value_type_id")
    private Long listValueTypeId;
    
    public AttrListValue(Long attributeId, Long listValueTypeId) {
        this.attributeId = attributeId;
        this.listValueTypeId = listValueTypeId;
    }
    
    public AttrListValue() {}
    
    public Long getAttributeId() {
        return attributeId;
    }

    public void setAttributeId(Long attributeId) {
        this.attributeId = attributeId;
    }
    
    public Long getListValueTypeId() {
        return listValueTypeId;
    }

    public void setListValueTypeId(Long listValueTypeId) {
        this.listValueTypeId = listValueTypeId;
    }
    

    @Override
    public String toString() {
        return "attributeId : " + getAttributeId() +
                ", listValueTypeId : " + getListValueTypeId();
    }
}

src/main/java/org/bitbucket/dms/model/Attribute.java
package org.bitbucket.dms.model;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.*;
import java.util.List;

/**
 * Author: Popov Dmitry
 */


@SuppressWarnings("JpaDataSourceORMInspection")
@Entity
//@NamedQuery(name="Attribute.getAll", query="SELECT a FROM Attribute a")
@Table(name="attributes")
public class Attribute extends GenericEntity{

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name="attribute_id")
    private Long id;
    private String name;

    @Column(name="description")
    private String description;

    @ManyToOne
    @JoinColumn(name="atr_type")
    private DataType dataType;

    @Column(name = "properties")
    private String properties;


    @ManyToOne
    @JoinTable(
            name="attr_list_value"
            , joinColumns={
            @JoinColumn(name="attribute_id")
    }
            , inverseJoinColumns={
            @JoinColumn(name="list_value_type_id")
    }
    )
    private ListValueType listValueType;


    public Attribute(String name, String description, DataType dataType, String properties, ListValueType listValueType) {
        this.name = name;
        this.description = description;
        this.dataType = dataType;
        this.properties = properties;
        this.listValueType = listValueType;
    }

    public Attribute(String name, String description, DataType dataType, String properties) {
        this.name = name;
        this.description = description;
        this.dataType = dataType;
        this.properties = properties;
    }

    public Attribute() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public DataType getDataType() {
        return dataType;
    }

    public void setDataType(DataType dataType) {
        this.dataType = dataType;
    }

    public String getTypeName ()
    {
        return dataType.getName();
    }

    public void setProperties(String properties){
        this.properties = properties;
    }
    public String getProperties(){
        return properties;
    }

    public ListValueType getListValueType() {
        return listValueType;
    }

    public void setListValueType(ListValueType listValueType) {
        this.listValueType = listValueType;
    }

    @Override
    public String toString() {
        return "Attribute{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", dataType=" + dataType +
                ", properties='" + properties + '\'' +
                ", listValueType=" + listValueType +
                '}';
    }

    public boolean equals(Object  o) {
        Attribute a=(Attribute) o;
        return a.getId().equals(this.getId());
    }
    public int hashCode() {
        // you pick a hard-coded, randomly chosen, non-zero, odd number
        // ideally different for each class
        return new HashCodeBuilder(17, 37).
                append(id).
                append(name).
                append(description).
                append(properties).
                toHashCode();
    }
}

src/main/java/org/bitbucket/dms/model/DataType.java
package org.bitbucket.dms.model;

import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.*;


/**
 * Author: Popov Dmitry
 */


@Entity
@NamedQuery(name="DataType.getAll", query="SELECT a FROM DataType a")
@Table(name="data_types")
public class DataType {

    @Id
    private Long id;
    private String name;

    public DataType(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public DataType() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).
                append("name", name).toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DataType dataType = (DataType) o;

        if (id != null ? !id.equals(dataType.id) : dataType.id != null) return false;
        return name != null ? name.equals(dataType.name) : dataType.name == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}

src/main/java/org/bitbucket/dms/model/Doc.java
package org.bitbucket.dms.model;

import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.*;
import java.util.List;


/**
 * Author: Popov Dmitry
 */


@Entity
@Table(name = "documents_def")
public class Doc {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    private String name;
    private String hash;


    @ManyToMany
    @JoinTable(
            name = "docs_changes"
            , joinColumns = {
            @JoinColumn(name = "doc_id")
    }
            , inverseJoinColumns = {
            @JoinColumn(name = "attribute_id")
    }
    )
    private List<Attribute> attributes;


    @ManyToMany
    @JoinTable(
            name = "docs_changes"
            , joinColumns = {
            @JoinColumn(name = "doc_id")
    }
            , inverseJoinColumns = {
            @JoinColumn(name = "type_id")
    }
    )
    private List<Type> types;

    @ManyToMany
    @JoinTable(
            name = "docs_changes"
            , joinColumns = {
            @JoinColumn(name = "doc_id")
    }
            , inverseJoinColumns = {
            @JoinColumn(name = "list_value_type_id")
    }
    )
    private List<ListValueType> listValueTypes;

    @ManyToMany
    @JoinTable(
            name = "docs_changes"
            , joinColumns = {
            @JoinColumn(name = "doc_id")
    }
            , inverseJoinColumns = {
            @JoinColumn(name = "list_value_id")
    }
    )
    private List<ListValue> listValues;


    public Doc(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    public Doc() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public List<Attribute> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
        this.attributes = attributes;
    }

    public List<Type> getTypes() {
        return types;
    }

    public void setTypes(List<Type> types) {
        this.types = types;
    }

    public List<ListValueType> getListValueTypes() {
        return listValueTypes;
    }

    public void setListValueTypes(List<ListValueType> listValueTypes) {
        this.listValueTypes = listValueTypes;
    }

    public List<ListValue> getListValues() {
        return listValues;
    }

    public void setListValues(List<ListValue> listValues) {
        this.listValues = listValues;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).
                append("name", name).toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Doc dataType = (Doc) o;

        if (id != null ? !id.equals(dataType.id) : dataType.id != null) return false;
        return name != null ? name.equals(dataType.name) : dataType.name == null;

    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        return result;
    }
}

src/main/java/org/bitbucket/dms/model/GenericEntity.java
package org.bitbucket.dms.model;

public class GenericEntity {
}

src/main/java/org/bitbucket/dms/model/ListValue.java
package org.bitbucket.dms.model;

import javax.persistence.*;

import org.apache.commons.lang3.builder.ToStringBuilder;

import java.math.BigInteger;

@SuppressWarnings("JpaDataSourceORMInspection")
@Entity
@NamedQuery(name="ListValue.getAll", query="SELECT l FROM ListValue l")
@Table(name="list_values")

public class ListValue extends GenericEntity {
    @Id
    @Column(name="list_value_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long listValueId;

    @ManyToOne(fetch=FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE})
    @JoinColumn(name="list_value_type_id", insertable = true, updatable = true)
    private ListValueType listValueType;

    @Column(name="value")
    private String value;

    public ListValue(Long listValueId, BigInteger listValueTypeId, String value) {
    this.listValueId = listValueId;
    //this.listValueType = listValueTypeId;
    this.value = value;

    }

    public ListValue() {
    }

    public Long getListValueId() {
        return listValueId;
    }
    public void setListValueId(Long listValueId) {
        this.listValueId = listValueId;
    }

    public ListValueType getListValueType() {
        return listValueType;
    }

    public void setListValueType(ListValueType listValueType) {
        this.listValueType = listValueType;
    }

    public String getValue(){
    	return value;
    }
    public void setValue(String value){
    	this.value = value;
    }
   
    @Override
    public String toString(){
		 return getValue();
    	
    	
    }
}

src/main/java/org/bitbucket/dms/model/ListValueType.java
package org.bitbucket.dms.model;

import javax.persistence.*;

import java.util.List;

@SuppressWarnings("JpaDataSourceORMInspection")
@Entity
@NamedQuery(name = "ListValueType.getAll", query = "SELECT l FROM ListValueType l")

@Table(name = "list_value_type")

public class ListValueType extends GenericEntity{
	@Id
    @Column(name = "list_value_type_id")
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    @Column(name = "name")
    private String name;

    @OneToMany(mappedBy = "listValueType",fetch = FetchType.EAGER)
    private List<ListValue> listValues;

    public List<ListValue> getListValues() {
    	
        return listValues;
    }

    public void setListValues(List<ListValue> listValues) {
        this.listValues = listValues;
    }

    public ListValueType(Long id, String name) {
        this.id = id;
        this.name = name;

    }

    public ListValueType() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long listValueTypeId) {
        this.id = listValueTypeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Override
    public String toString() {
    	
        return  "list_value_type_id " + getId() +
        		" name " + getName();
    }
    public boolean equals(Object  o) {
        ListValueType a=(ListValueType) o;
        return a.getId().equals(this.getId());
    }
}

src/main/java/org/bitbucket/dms/model/Value.java
package org.bitbucket.dms.model;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@NamedQuery(name = "Values.getAll", query = "SELECT v FROM Value v")
@Table(name = "values")
public class Value extends GenericEntity{
    @Id
    @Column(name = "value_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @ManyToOne
    @JoinColumn(name = "object_id")
    private ObjectModel obj;
    @ManyToOne (fetch = FetchType.EAGER)
    @JoinColumn(name = "attribute_id")
    private Attribute attribute;
    @Column(name = "value_int")
    private Long numValue;
    @Column(name = "value_string")
    private String stringValue;
    @Column(name = "value_date")
    private Date dateValue;

    @ManyToOne
    @JoinColumn(name = "value_listvalue_id")
    private ListValue listValue;



    public Value() {
    }

    public Value(ObjectModel obj, Attribute attribute, Long numValue, String stringValue, Date dateValue) {
        this.obj = obj;
        this.attribute = attribute;
        this.numValue = numValue;
        this.stringValue = stringValue;
        this.dateValue = dateValue;
    }

    public String getUniValue() {

        Long type = attribute.getDataType().getId();
        if (type == 1L) return numValue.toString();
        if (type == 2L) return stringValue;
        if (type == 3L) return dateValue.toString();
        if (type == 4L) return listValue.getValue(); //"here must be displayed value from list";
        return "value is missing";

    }

    public Long getId() {
        return id;
    }

    public Attribute getAttribute() {
        return attribute;
    }

    public void setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }

    public Long getNumValue() {
        return numValue;
    }

    public void setNumValue(Long numValue) {
        this.numValue = numValue;
    }

    public String getStringValue() {
        return stringValue;
    }

    public void setStringValue(String stringValue) {
        this.stringValue = stringValue;
    }

    public Date getDateValue() {
        return dateValue;
    }

    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }

    public ObjectModel getObj() {
        return obj;
    }

    public void setObj(ObjectModel obj) {
        this.obj = obj;
    }
}

src/main/java/org/bitbucket/dms/views/SessionBean.java
package org.bitbucket.dms.views;

import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
 
public class SessionBean {
 
    public static HttpSession getSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }
 
    public static HttpServletRequest getRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance()
                .getExternalContext().getRequest();
    }
 
    public static String getUserName() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
        return session.getAttribute("username").toString();
    }
 
}

src/main/webapp/all_references_view.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="templates/template.xhtml">

    <ui:define name="metadata">
    </ui:define>
    <ui:define name="content">


        <h:body>
            <h:form id="reference_view_form">
                <p:button value="Create Reference"  outcome="reference_create" icon="ui-icon-circle-plus" />


                <p:contextMenu for="references">
                    <p:menuitem value="View" update="referenceDetail" icon="ui-icon-search" oncomplete="PF('referenceDialog').show()"/>
                    <p:menuitem value="Edit" update="references" icon="ui-icon-pencil" action="#{allReferencesView.editReference}"/>
                    <p:menuitem value="Delete" action="#{allReferencesView.deleteReference}" update="@form" icon="ui-icon-close" ajax="true"/>
                </p:contextMenu>
                <p:dataTable id="references" var="reference" value="#{allReferencesView.references}" rowKey="#{reference.id}"
                             selection="#{allReferencesView.selectedReference}" selectionMode="single" style="width: 100%">

                    <f:facet name="header">
                        References:
                    </f:facet>

                    <p:column headerText="Ref from">
                        <h:outputText value="#{reference.object.name}" />
                    </p:column>

                    <p:column headerText="Ref to">
                        <h:outputText value="#{reference.reference.name}" />
                    </p:column>

                    <p:column headerText="Attribute">
                        <h:outputText value="#{reference.attribute.name}" />
                    </p:column>

                    <p:column headerText="Order">
                        <h:outputText value="#{reference.order}" />
                    </p:column>
                </p:dataTable>

                <p:dialog header="Reference Info" widgetVar="referenceDialog" appendToBody="false" modal="false" showEffect="fade" hideEffect="fade" resizable="false">
                    <p:outputPanel id="referenceDetail" style="text-align:center;">
                        <p:panelGrid columns="2" rendered="#{not empty allReferencesView.selectedReference}" columnClasses="label,value">
                            <f:facet name="header">
                                <h:outputText value="Reference details" />
                            </f:facet>
                            <h:outputText value="Id:" />
                            <h:outputText value="#{allReferencesView.selectedReference.id}" />

                            <h:outputText value="Name" />
                            <h:outputText value="#{allReferencesView.selectedReference.object.name}" />

                            <h:outputText value="ReferenceType" />
                            <h:outputText value="#{allReferencesView.selectedReference.reference.name}" />

                            <h:outputText value="Description" />
                            <h:outputText value="#{allReferencesView.selectedReference.attribute.name}" />

                            <h:outputText value="Properties" />
                            <h:outputText value="#{allReferencesView.selectedReference.order}" />
                        </p:panelGrid>
                    </p:outputPanel>
                </p:dialog>
            </h:form>
        </h:body>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/attribute_edit.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="templates/template.xhtml">

    <ui:define name="metadata">
    </ui:define>
    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="id" value="#{attributeEditView.id}" />
            <f:viewAction action="#{attributeEditView.init}" />
        </f:metadata>
        <h:head>
            <title>Attribute edit</title>
        </h:head>
        <h:body>
            <h:form id="form">
                <h:panelGrid columns="2"  cellpadding="5">
                    <p:outputLabel value="Id : " />
                    <p:outputLabel id="id" value="#{attributeEditView.attribute.id}"></p:outputLabel>

                    <p:outputLabel for="name" value="Name : " />
                    <p:inputText id="name" value="#{attributeEditView.attribute.name}"></p:inputText>

                    <p:outputLabel for="type" value="Type: " />
                    <p:outputLabel id="type" value="#{attributeEditView.attribute.typeName}" ></p:outputLabel>

                    <p:outputLabel for="listValueType" value="List type: " rendered="#{attributeEditView.isList()}"/>
                    <p:outputLabel id="listValueType" value="#{attributeEditView.attribute.listValueType.name}" rendered="#{attributeEditView.isList()}"/>


                    <p:outputLabel for="description" value="Description : " />
                    <p:inputTextarea rows="1" cols="33" id="description" value="#{attributeEditView.attribute.description}"></p:inputTextarea>

                    <p:outputLabel for="properties" value="Properties : " />
                    <p:inputTextarea rows="1" cols="33" id="properties" value="#{attributeEditView.attribute.properties}"></p:inputTextarea>

                </h:panelGrid>
                <p:commandButton id="cancel" value="Cancel" action="#{attributeEditView.cancel}" oncomplete = "window.history.back();" ajax="true" />
                <p:commandButton id="update" value="OK" action="#{attributeEditView.update}" oncomplete = "window.history.back();" ajax="true"/>
            </h:form>
        </h:body>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/single_object_view.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                template="templates/template.xhtml">

    <ui:define name="metadata">
    </ui:define>
    <ui:define name="content">
        <f:metadata>
            <f:viewParam name="id" value="#{singleObjectView.id}" />
            <f:viewAction action="#{singleObjectView.init}" />
        </f:metadata>
        <h:head>
            <title>Object</title>
        </h:head>
        <h:body>
            <h:form id="form">
                <h:panelGrid columns="2" columnClasses="column" cellpadding="5">

                    <h:outputLabel for="id" value="ID:" />
                    <p:inplace id="id" editor="false">
                        <p:inputText value="#{singleObjectView.object.id}" required="true" label="text" />
                    </p:inplace>


                    <h:outputLabel for="name" value="Name:" />
                    <p:inplace id="name" editor="true">
                        <p:inputText value="#{singleObjectView.object.name}" required="true" label="text" />
                    </p:inplace>

                    <h:outputLabel for="type" value="Type:" />
                    <p:link id="type" outcome="type_edit" value="#{singleObjectView.object.type.name}">
                        <f:param name="id" value="#{singleObjectView.object.type.id}" />
                    </p:link>

                    <h:outputLabel for="description" value="Description:" />
                    <p:inplace id="description" editor="true">
                        <p:inputTextarea value="#{singleObjectView.object.description}" rows="1" cols="33" />
                    </p:inplace>

                    <h:outputLabel for="parent" value="Parent:" />
                    <p:link id="parent" outcome="single_object_view" value="#{singleObjectView.object.parent.name}">
                        <f:param name="id" value="#{singleObjectView.object.parent.id}" />
                    </p:link>

                    <h:outputLabel for="project" value="Project:" />
                    <p:link id="project" outcome="single_object_view" value="#{singleObjectView.object.projectID.name}">
                        <f:param name="id" value="#{singleObjectView.object.projectID.id}" />
                    </p:link>

                    <h:outputLabel for="order" value="Order:" />
                    <p:inplace id="order" editor="true">
                        <p:inputText value="#{singleObjectView.object.orderID}" required="true" label="text" />
                    </p:inplace>


                </h:panelGrid>
                <p:commandButton action="#{singleObjectView.deleteObject()}" value="Delete" icon="ui-icon-close"  ajax="true"/>
                <p:tabView>
                    <p:tab title="Attributes">
                        <h:form id="values_view_form">
                            <p:dataTable id="values" var="value" value="#{singleObjectView.values}" rowKey="#{value.id}"
                                         selection="#{singleObjectView.selectedValue}" selectionMode="single" style="width: 100%">
                                <f:facet name="header">
                                    Attribute values for #{singleObjectView.object.name}
                                </f:facet>
                                <p:column headerText="Attribute">
                                    <p:link outcome="attribute_edit" ajax="true">
                                        <f:param name="id" value="#{value.attribute.id}" />
                                        <h:outputText value="#{value.attribute.name}" />
                                    </p:link>
                                </p:column>
                                <p:column headerText="Value">
                                    <h:outputText value="#{value.uniValue}" />
                                </p:column>
                            </p:dataTable>
                        </h:form>
                    </p:tab>
                    <p:tab title="References">
                        <h:form id="reference_view_form">
                            <p:contextMenu for="references">
                                <p:menuitem value="View" update="referenceDetail" icon="ui-icon-search" oncomplete="PF('referenceDialog').show()"/>
                                <p:menuitem value="Edit" update="references" icon="ui-icon-pencil" action="#{objectReferencesView.editReference}"/>
                                <p:menuitem value="Delete" action="#{objectReferencesView.deleteReference}" update="@form" icon="ui-icon-close" ajax="true"/>
                            </p:contextMenu>
                            <p:dataTable id="references" var="reference" value="#{singleObjectView.references}" rowKey="#{reference.id}"
                                         selection="#{singleObjectView.selectedReference}" selectionMode="single" style="width: 100%">
                                <f:facet name="header">
                                    References for #{singleObjectView.object.name}
                                </f:facet>
                                <p:column headerText="Attribute">
                                    <p:link id="attribute" outcome="attribute_edit" ajax="true">
                                        <f:param name="id" value="#{reference.attribute.id}" />
                                        <h:outputText value="#{reference.attribute.name}" />
                                    </p:link>
                                </p:column>
                                <p:column headerText="Ref to">
                                    <p:link id="reftoobj" outcome="single_object_view" ajax="true">
                                        <f:param name="id" value="#{reference.reference.id}" />
                                        <h:outputText value="#{reference.reference.name}" />
                                    </p:link>
                                </p:column>

                                <p:column headerText="Order">
                                    <h:outputText value="#{reference.order}" />
                                </p:column>
                            </p:dataTable>

                            <p:dialog header="Reference Info" widgetVar="referenceDialog" appendToBody="false" modal="false" showEffect="fade" hideEffect="fade" resizable="false">
                                <p:outputPanel id="referenceDetail" style="text-align:center;">
                                    <p:panelGrid columns="2" rendered="#{not empty objectReferencesView.selectedReference}" columnClasses="label,value">
                                        <f:facet name="header">
                                            <h:outputText value="Reference details" />
                                        </f:facet>
                                        <h:outputText value="Id:" />
                                        <h:outputText value="#{singleObjectView.selectedReference.id}" />

                                        <h:outputText value="Name" />
                                        <h:outputText value="#{singleObjectView.selectedReference.object.name}" />

                                        <h:outputText value="ReferenceType" />
                                        <h:outputText value="#{singleObjectView.selectedReference.reference.name}" />

                                        <h:outputText value="Description" />
                                        <h:outputText value="#{singleObjectView.selectedReference.attribute.name}" />

                                        <h:outputText value="Properties" />
                                        <h:outputText value="#{singleObjectView.selectedReference.order}" />
                                    </p:panelGrid>
                                </p:outputPanel>
                            </p:dialog>
                        </h:form>
                    </p:tab>
                </p:tabView>
            </h:form>
        </h:body>
    </ui:define>

</ui:composition>
</html>